name: Build Wheels

on: [push, pull_request]
  #push:
   # tags:
    #  - '*'
env:
  CIBW_SKIP: cp27-* cp33-* cp34-* cp35-* pp27* pp36* pp37*

jobs:
  build_wheels:
    name: Build wheels on ${{matrix.arch}} for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [x86_64, aarch64]
        #os: [ubuntu-20.04, windows-2019, macos-latest]
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        if:  ${{matrix.arch}} == 'aarch64'

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0
        # to supply options, put them in 'env', like:
        env:
          CIBW_ARCHS_LINUX: ${{matrix.arch}}
          CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-*"
          CIBW_BEFORE_BUILD: pip install oldest-supported-numpy

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
